// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJmvAm4FQarCh2QOkWph49iigBw1QEfc',
    appId: '1:691689802255:web:68962e53d235d68b50717a',
    messagingSenderId: '691689802255',
    projectId: 'poject-ecde8',
    authDomain: 'poject-ecde8.firebaseapp.com',
    storageBucket: 'poject-ecde8.appspot.com',
    measurementId: 'G-WVZBW2J3WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrNe34eSfLIynlFtt-zOZ9ZQFDZBlzPJk',
    appId: '1:691689802255:android:85deec78d5b09d8d50717a',
    messagingSenderId: '691689802255',
    projectId: 'poject-ecde8',
    storageBucket: 'poject-ecde8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6rXCW8LIABKC1jcG6E12MsjFPhaDruuY',
    appId: '1:691689802255:ios:e0d49b1f9c2d7ad850717a',
    messagingSenderId: '691689802255',
    projectId: 'poject-ecde8',
    storageBucket: 'poject-ecde8.appspot.com',
    iosBundleId: 'com.example.latihan2',
  );
}
